refactor(git-cleanup): Automatically finish selecting branches if selecting all.
  - Don't offer an all choice if there's only one branch.
  - Don't offer a done branch, use CTRL-D instead.

diff --git a/bin/git-cleanup b/bin/git-cleanup
--- a/bin/git-cleanup
+++ b/bin/git-cleanup
@@ -29,28 +29,32 @@ select_elements() {
     done
 
     while true; do
-        local opts=( "${arr[@]}" "All of them" "Done" )
+        local opts=( "All of them" "${arr[@]}" )
+        local end=1
         select opt in "${opts[@]}"; do
-            if [[ "${REPLY}" -le "${num}" ]]; then
-                if [[ "${opt}" = ☐* ]]; then
-                    arr[REPLY-1]="☑ ${opt#* }"
-                else
-                    arr[REPLY-1]="☐ ${opt#* }"
-                fi
-            elif [[ "${REPLY}" -eq $((num+1)) ]]; then
+            # CTRL-D exits the select statement without executing anything in
+            # this block. `end` will be set if that happens.
+            end=
+
+            if ((REPLY == 1)); then
                 # All of them
                 for ((i=0; i < num; i++)); do
                     if [[ "${arr[$i]}" = ☐* ]]; then
                         arr[i]="☑ ${arr[$i]#* }"
                     fi
                 done
-            elif [[ "${REPLY}" -eq $((num+2)) ]]; then
-                local done=1
+                end=1
+            elif ((REPLY-2 < num)); then
+                if [[ "${opt}" = ☐* ]]; then
+                    arr[REPLY-2]="☑ ${opt#* }"
+                else
+                    arr[REPLY-2]="☐ ${opt#* }"
+                fi
             fi
             break
         done
 
-        if [[ -n "${done:-}" ]]; then
+        if [[ -n "${end:-}" ]]; then
             break
         fi
     done
@@ -65,10 +69,14 @@ select_elements() {
     mapfile -t "${arr_name}" < <(IFS=$'\n'; echo "${selected[*]}")
 }
 
-
-echo
-echo "Found ${#gone[@]}} gone branches. Which of them would you like to cleanup?"
-select_elements gone
+if [[ "${#gone[@]}" -eq 1 ]]; then
+    echo
+    dotfiles::user_permission "Found 1 gone branch (${gone[0]}). Would you like to clean it up? "
+else
+    echo
+    echo "Found ${#gone[@]} gone branches. Which of them would you like to cleanup?"
+    select_elements gone
+fi
 
 [[ "${#gone[@]}" -eq 0 ]] && exit 0
 
@@ -104,7 +112,13 @@ else
     extra_branches=()
 fi
 
-if [[ "${#extra_branches[@]}" -gt 0 ]]; then
+if [[ "${#extra_branches[@]}" -eq 1 ]]; then
+    echo
+    if ! dotfiles::user_permission "Found 1 additional branches on the gone branches (${extra_branches[0]}). Would you like to clean it up? "; then
+        extra_branches=()
+    fi
+elif [[ "${#extra_branches[@]}" -gt 1 ]]; then
+    echo
     echo "Found ${#extra_branches[@]} additional branches on the gone branches. Which of them would you like to cleanup?"
     select_elements extra_branches
 fi
